### ISSUE TITLE
Supprimer capitalize dans résultats de recherche

### ISSUE THREAD

**Issue by AntoineAugusti** [annuaire-entreprises-data-gouv-fr/site#100]
Pourquoi avoir une transformation du nom ici ?

https://github.com/etalab/annuaire-entreprises-site/blob/efd2cfbc87bcbea4a84d163fe86958a7508bc0fe/components/results-list/index.tsx#L28

https://annuaire-entreprises.data.gouv.fr/rechercher?terme=dinum fait disparaitre les majuscule dans l'acronyme.

Pour les micro entrepreneurs, le nom de famille apparaît en minuscule alors que la dénomination sur la page individuelle comprend des majuscules bien placées.

**Comment by AntoineAugusti** [comment]
Très heureux d'utiliser l'issue 💯 pour cette suggestion

**Comment by XavierJp** [comment]
merci pour l'issue. Ce code n'existant plus je ferme l'issue.
