### ISSUE TITLE
AgentConnect ne fonctionne pas en staging

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1002]

**Comment by johangirod** [comment]
Je soupçonne que cela soit tout simplement dû au fait que le domaine `https://staging.annuaire-entreprises.data.gouv.fr/` soit protégé par HTTP basic auth, et que par conséquent, le callback ne fonctionne pas.

D'où ma question : est-ce bien nécessaire ? Nos review app sont publics, la donnée est publique. Si on souhaite éviter les scraping ne peut-on pas activer les mêmes protections que la prod ? 

Sinon, serait-il envisageable de rendre publique les routes de callback `/api/auth/*` ?

**Comment by johangirod** [comment]
Je soupçonne que cela soit tout simplement dû au fait que le domaine `https://staging.annuaire-entreprises.data.gouv.fr/` soit protégé par HTTP basic auth, et que par conséquent, le callback ne fonctionne pas.

D'où ma question : est-ce bien nécessaire ? Nos review app sont publics, la donnée est publique. Si on souhaite éviter les scraping ne peut-on pas activer les mêmes protections que la prod ? 

Sinon, serait-il envisageable de rendre publique les routes de callback `/api/auth/*` ?

@MKCG

**Comment by XavierJp** [comment]
Brilliant, c'est forcément ça l'explication. par contre pas chaud d'enlever le basic auth. Ca nous donne certes un peu de taff ponctuellement comme par exemple aujourd'hui ou le fait de devoir connaitre le couple id/mdp.

Mais l'alternative c'est élargir la surface de scrapping, et donc de monitoring.
Et on a eu le cas du scrapping de staging par le passé et ca a eu pour conséquence trop réelle un clash avec l'INSEE qui nous a demandé de ne plus utiliser leur API. Au total plusieurs journées de dev dépensées la dedans.

**Comment by XavierJp** [comment]
Je vote plus pour exclure les routes `/api/auth/*`de la basic authentication si c'est pas trop galère

**Comment by MKCG** [comment]
Au delà de la question du scraping : le staging doit permettre d'identifier des problèmes avant qu'ils n'arrivent en prod et permettre de disposer d'un environnement ISO prod sur lequel reproduire des incidents. Ce qui implique que les accès y soient restreints.

C'est possible d'exclure les routes `/api/auth/*` de l'authentification basique, j'ajoute ça.

**Comment by MKCG** [comment]
Je viens de les exclure mais ça n'a pas d'effet : une erreur remonte dans sentry lors de l'appel client.grant (génération d'access token en fonction du code d'accès fourni)

**Comment by johangirod** [comment]
Ah si ça a un effet : on n'avait pas les erreurs avant :)
Je regarde ça.
