### ISSUE TITLE
[BUG Ally] Link in tooltip breaks keyboard navigation

### ISSUE THREAD

**Issue by johangirod** [annuaire-entreprises-data-gouv-fr/site#1062]
![image](https://github.com/annuaire-entreprises-data-gouv-fr/site/assets/1775934/dc3648ee-0f23-48d8-b8bd-8c7fe53d8022)

Use tab to go from link to link, when the modal appears and then a last tab : the position is reset. 
Link / focusable element in tooltip is explicitly discouraged by W3C.

**Comment by XavierJp** [comment]
I see. I added the link back as I had completly forgotten that the label was in fact both a hover and a link. So I did not even tried to click on it.

I suggest we make the En savoir plus non-focusable as : 
- with a screen reader you know that "Adresse Postale" is a link, no need to have focus on "En savoir plus"
- without a screen reader, you very likely miss the fact that "Adresse Postale" is a link, and "En savoir plus" make sense
