### ISSUE TITLE
[Contenu - pages du footer] Corriger les coquilles identifiées

### ISSUE THREAD

**Issue by Jonathan2051** [annuaire-entreprises-data-gouv-fr/site#1100]
J'ai identifié 72 coquilles dans le contenu des pages accessibles via le footer :

- [x] **https://annuaire-entreprises.data.gouv.fr/lp/entrepreneur-spectacles-vivants**
- remplissent -> remplisse
- C’est une direction générale du ministère des finances -> C’est une direction générale du ministère des Finances
- Le Ministère de la Culture -> Le ministère de la Culture

- [x] **https://annuaire-entreprises.data.gouv.fr/partager**
- couriers -> courriers
- fréquement -> fréquemment

- [x] **https://annuaire-entreprises.data.gouv.fr/donnees/sources**
- Code Officiel Géographiques (COG) -> Code Officiel Géographique (COG) ⚠️ X 2

- [x] **https://annuaire-entreprises.data.gouv.fr/donnees/api-entreprises**
- l’Annuaires des Entrepirses -> l’Annuaires des Entreprise 

- [x] **https://annuaire-entreprises.data.gouv.fr/donnees/api**
- accèdant -> accédant X 19

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/donnees-financieres**
- Les données financieres des entreprises individuelles -> Les données financières des entreprises individuelles
- des Urssafs -> des Urssaf
- du Ministère de l'Économie et des Finances -> du ministère de l'Économie et des Finances 

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/entrepreneur-spectacles-vivants**
- 5 ans renouvelable -> renouvelables
- qu'au moins un de ses membres les remplissent -> qu'au moins un de ses membres les remplisse
- du Ministère de la Culture -> du ministère de la Culture

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/extrait-kbis**
- vigeur -> vigueur

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/professionnels-bio**
- l’Institut NAtional de l’Origine et de la qualité (INAO) -> l’Institut National de l’Origine et de la qualité (INAO)

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/qualiopi-organisme-formation**
- Le certification -> La certification X 3
- le Ministère du travail, du plein emploi et de l’insertion ->  le ministère du Travail, du Plein Emploi et de l’Insertion ⚠️ X 2

- [x] **https://annuaire-entreprises.data.gouv.fr/faq/societe-a-mission**
- intègrant -> intégrant

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/association**
- elle oœuvre -> elle oeuvre

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/entrepreneur-de-spectacles-vivants**
- 5 ans renouvelable -> renouvelables
- l’obtention d’un récépissé délivrée -> l’obtention d’un récépissé délivré
- auprès du Ministère de la culture -> auprès du ministère de la Culture
- et doit pas avoir fait l'objet -> et ne doit pas avoir fait l’objet

- [ ] **https://annuaire-entreprises.data.gouv.fr/definitions/etablissement**
- L’établissement est une dénomination juridique désignant l'unité de production d'une entreprise, liée à son unité légale. Ou autre dénomination utilisée est celle d'établissement principale ou secondaire où :
L'établissement principal renvoie à l'unité légale (traditionnellement le siège social)
L'établissement secondaire (ou les établissements secondaire quand ils sont plusieurs) désigne un site de production.

->

- L'établissement est une dénomination juridique désignant l'unité de production d'une entreprise liée à son unité légale. L’autre dénomination utilisée est celle d'établissement principale ou secondaire :
L'établissement principal renvoie à l'unité légale (traditionnellement le siège social)
L'établissement secondaire désigne un site de production

——

établissements basées en France -> établissements basés en France

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/index-egapro-egalite-professionnelle-entre-les-femmes-et-les-hommes**
- le niveau d'égalité égalité professionnelle ->  le niveau d’égalité professionnelle
- le moteur de recherche du ministère du travail -> le moteur de recherche du ministère du Travail 

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/label-professionnel-du-bio**
- l’Institut NAtional de l’Origine et de la qualité (INAO) -> l’Institut National de l’Origine et de la qualité (INAO)

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/numero-siren**
- document commerciaux -> documents commerciaux

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/personne-morale**
-inconvénient -> inconvénients

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/personne-physique**
- vous pourrez retrouver n’importe quelle entreprise individuelles ou auto-entreprises en France -> vous pourrez retrouver n’importe quelle entreprise individuelle ou auto-entreprise en France

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/societe-a-mission**
- Issue de la loi pacte en 2019 -> Issue de la loi Pacte en 2019 
- quel que soit leur nature juridique -> quelle que soit leur nature juridique
- il faut la déclarer comme tel -> il faut la déclarer comme telle

- [x] **https://annuaire-entreprises.data.gouv.fr/definitions/tva-intracommunautaire**
- disposant d'un numéro de Numéro de TVA intracommunautaire ? -> disposant d'un numéro de TVA intracommunautaire ? ⚠️ X 2
- Une entreprise peut-elle avoir plusieurs numéro de TVA intracommunautaire ? -> Une entreprise peut-elle avoir plusieurs numéros de TVA intracommunautaire ?
- elle dépend du régime de la franchise en base sans avoir solliciter le numéro auprès de son SIE de rattachement -> elle dépend du régime de la franchise en base et n’a pas sollicité le numéro auprès de son SIE de rattachement
- Dans les cas ou le numéro n’est pas accesible -> Dans les cas ou le numéro n’est pas accessible
- avoir plusieurs numéro -> avoir plusieurs numéros ⚠️ X 2
- pour chacun de ses code d’activité ->  pour chacun de ses codes d’activité

- [x] **https://annuaire-entreprises.data.gouv.fr/a-propos/comment-ca-marche**
- Les fiches de l’Annuaire regroupe -> Les fiches de l’Annuaire regroupent
- auprès du ministère du travail -> auprès du ministère du Travail
- Ministère de l'Éducation nationale et de la jeunesse (MENJ) -> Ministère de l'Éducation nationale et de la Jeunesse (MENJ)

- [x] **https://annuaire-entreprises.data.gouv.fr/administration**
- dans les bulletins d'annonces légale -> dans les bulletins d'annonces légales
- sur les sujet numérique -> sur les sujets du numérique
- du ministère des finances -> du ministère des Finances 
- Le ministère du travail publie -> Le ministère du Travail publie
- Le ministère de l’interieur publie -> Le ministère de l’Intérieur publie
- tout autre personne morale -> toute autre personne morale 
- des acheteurs privés et public -> des acheteurs privés et publics

- [x] **https://annuaire-entreprises.data.gouv.fr/a-propos/stats**
- est un un utilisateur récurrent -> est un utilisateur récurrent 
- au questionnaire de statisfaction -> au questionnaire de satisfaction
- Les réponses au formulaire de statisfaction -> Les réponses au formulaire de satisfaction

- [x] **https://annuaire-entreprises.data.gouv.fr/a-propos/budget**
- le projet est une experimentation -> le projet est une expérimentation

- [x] **https://annuaire-entreprises.data.gouv.fr/a-propos/equipe**
- sur une informations affichée -> sur une information affichée

- [ ] **https://annuaire-entreprises.data.gouv.fr/vie-privee**
- aux services numérique -> aux services numérique
- suivant la cessation de l’activité de l’entreprise, l’association et le service public concerné -> suivant la cessation de l’activité de l’entreprise, l’association ou le service public concerné
- d’une dizaine de minute -> d’une dizaine de minutes
- Dans le cas où nous ne parvenons pas à vous identifier, nous pouvons être amenés -> Dans le cas où nous ne parviendrions pas à vous identifier, nous pourrions être amenés
- Les membres du service numérique l’Annuaire les entreprises -> Les membres du service numérique l’Annuaire des entreprises
- doivent être consenti par l’utilisateur -> doivent être consentis par l’utilisateur 
- 30 minute -> 30 minutes
- L’Anuaire des Entreprises utilise l’outil de mesure d’audience Matomo -> L’Annuaire des Entreprises utilise l’outil de mesure d’audience Matomo

- [x] **https://annuaire-entreprises.data.gouv.fr/historique-des-modifications**
- et le nombre de salarié -> et le nombre de salariés
- Ajout des représentation équilibrée -> Ajout des représentations équilibrées
- Ajout des dépots de comptes des associations -> Ajout des dépôts de comptes des associations
- Ajout du filtre par département dans le recherche avancée -> Ajout du filtre par département dans la recherche avancée

**Comment by XavierJp** [comment]
Merci @Jonathan2051 c'est précieux !
