### ISSUE TITLE
Enseigne / nom commercial

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1163]

**Comment by Anais-Tailhade** [comment]
- https://app.crisp.chat/website/064fca1b-bdd6-4a81-af56-9f38e40953ad/inbox/session_d5bf7379-e4ac-4a9c-ae83-b7a7d6261112/
- https://app.crisp.chat/website/064fca1b-bdd6-4a81-af56-9f38e40953ad/inbox/session_d8cd23fb-9728-4bce-86b8-9e72fdf1449f/
- https://support.etalab.gouv.fr/#ticket/zoom/77629
- https://app.crisp.chat/website/064fca1b-bdd6-4a81-af56-9f38e40953ad/inbox/session_f3012011-db5f-4625-8178-5526b352ffac/
- https://support.etalab.gouv.fr/#ticket/zoom/76021

**Comment by XavierJp** [comment]
- 491315891 - PRAETECH - ceci n'est pas un cas de dénomination usuelle
- 414645762 - AUTO ECOLE JLT (AUTO ECOLE DU MARNY)
	 - pas d'enseigne, de denomnaition du siege
	 - l'insee et l'inpi cachent AUTO ECOLE DU MARNY
 - 401224902 - CELINE ATTIAS CONSEIL (ADULTSHOP)
 	- pas d'enseigne pas de nom commerciald e siege
 	- insee et inpi cachent adultshop
	
@HAEKADI je propose de supprimer la dénominationUsuelleUniteLegale du nom complet

**Comment by XavierJp** [comment]
Nouvelle règle proposée : 
- var_denom_usuelle = denomUsuelleUniteLegale OU denomUsuelleEtablissementSiege OU null
- dénomination (var_denom_usuelle) (sigle)

**Comment by XavierJp** [comment]
@Anais-Tailhade du coup le nouvelle affichage ne corrige pas les cas mentionné plus haut, je pense qu'on peut leur indiquer l'explication suivante :   

```
Le nouvel affichage est le suivant : nous affichons dans la dénomination entre parenthèse le nom commercial. 

Pour corriger votre nom commercial vous devez le mettre a jour sur le guichet unique https://www.inpi.fr/comprendre-la-propriete-intellectuelle/les-autres-modes-de-protection/la-denomination-sociale-le-nom. Alors seulement il viendra corriger le nom affiché entre parenthèses.

Cette donnée vient de l'Insee, c'est la raison pour laquelle vous la retrouvez sur d'autres sites, elle n'est pas dans les bases de l'Inpi.
```
