### ISSUE TITLE
Dénomination d'une EI

### ISSUE THREAD

**Issue by AntoineAugusti** [annuaire-entreprises-data-gouv-fr/site#1217]
## Sujet du problème

La dénomination d'une EI fait apparaitre seulement la 1ère lettre du prénom et non le prénom complet.

Je n'ai pas indiqué ce nom sur l'INPI.

## Comment le reproduire ?

Aller à https://annuaire-entreprises.data.gouv.fr/entreprise/800919359

## Comportement attendu

La dénomination est "Antoine Augusti"

## Comportement actuel

La dénomination est "A Augusti". Ceci ne correspond pas au nom affiché sur la [page des résultats](https://annuaire-entreprises.data.gouv.fr/rechercher?terme=antoine+augusti).

**Comment by XavierJp** [comment]
Hello @AntoineAugusti, merci beaucoup pour la remontée de bug. Corrigée par #1218

**Comment by AntoineAugusti** [comment]
Merci pour le fix, c'était rapide 🏃🚀

**Comment by XavierJp** [comment]
🙏 C'etait un petit bug et je passais par la
