### ISSUE TITLE
Récupérer les données de DémarcheSimplifiée

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1225]
- faire le lien entre DS et les données de l'API de recherche
- publier le stock des services publics sur data.gouv

## Rapide analyse 

Une APi GraphQL qui permet de récupérer les dossiers d'une démarche et de les mettre a jour (soit changer de statut soit d'écrire un message)
https://doc.demarches-simplifiees.fr/api-graphql/les-mutations

Ma suggestions : un cron qui va régulièrement récupérer les derniers dossiers "acceptés" et les fait passer en archiver + envoi un message pour dire, dans X jours votre administration sera certifiée.

## Ok et ensuite ? 

Il faut trouver un moyen de stocker et publier. Je me dis que le mieux est peut etre est que le cron  : 
- le cron fetch la donnée
- la sauvegarde sur minio
- republiue sur un jdd dédié sur datagouv
- ce JDD devient une source parmi d'autre pour les repos d'infra et indexation

**Comment by MKCG** [comment]
Ok pour moi, sur la récupération DS fournit également une doc avec exemple sur l'usage de filtres de date de mise à jour ainsi que de curseurs : https://doc.demarches-simplifiees.fr/api-graphql/cas-dusages-exemple-dimplementation/pagination-synchroniser-une-demarche-a-forte-volumetrie-synchronisation

**Comment by XavierJp** [comment]
Ouep, j'aime beaucoup moins cette solution, car comme l'a dit Paul de DS, on est pas a l'abri qu'un usager modifie son dossier et change ainsi la date de mise a jour

**Comment by MKCG** [comment]
> Ouep, j'aime beaucoup moins cette solution, car comme l'a dit Paul de DS, on est pas a l'abri qu'un usager modifie son dossier et change ainsi la date de mise a jour

Je ne suis pas sûr de saisir : sur le lien que j'ai envoyé il s'agit de l'API à utiliser pour pouvoir réaliser le CRON permettant de fetch les données

**Comment by XavierJp** [comment]
Je prefere filtrer sur les statuts que sur la `date de dernière mise à jour` pour récupérer les dossiers `pending` car il y a beaucoup d'effets de bord possible avec la méthode `date de dernière mise à jour`. 

Par exemple si lors de notre script on décide d'envoyer un message, est ce que ca met a jour la `date de dernière mise à jour` ? Si oui il faut y penser pour ne pas boucler le lendemain a nouveau sur ces dossiers etc. 

L'alternative c'est de demander a l'API tous les dossiers "acceptés" une fois téléchargé : 
- on envoie un message a l'usager en mode "ce dossier va etre archivé, a partir de demain ton orga est validée"
- on archive le dossier pour que dans le prochain cron il ne fasse plus partie des dossiers "acceptés"

**Comment by HAEKADI** [comment]
Le besoin a évolué.
Nous allons dans un premier temps passer par Grist pour renseigner les demandes valider par Démarches simplifiées.
Puis publier les données sur data.gouv https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/411.
