### ISSUE TITLE
[FEATURE] Ne pas afficher  de lien vers le CDTN si l'idcc est inconnu

### ISSUE THREAD

**Issue by carolineBda** [annuaire-entreprises-data-gouv-fr/site#1255]
Bonjour,

Dans le cas d'[entreprise](https://annuaire-entreprises.data.gouv.fr/divers/531972586) ayant une IDCC inconnue, serait-il possible de ne pas afficher le lien vers le code du travail numérique ? Ces utilisateurs arrivent sur une 404 et nous ne pouvons pas vraiment les aider.

![Screenshot from 2024-10-07 14-59-01](https://github.com/user-attachments/assets/6c906f43-c9c0-4a93-9069-865483129599)

**Comment by carolineBda** [comment]
Je me permet d'ajouter une demande, pour pouvoir tracker le traffic qui vient d'annuaire-entreprise, est-ce qu'il serait possible d'ajouter sur tous vos liens vers code.travail.gouv.fr un query param avec `src_url=https://annuaire-entreprises.data.gouv.fr` ?

Merci :)

**Comment by rmonnier9** [comment]
Bonjour Caroline,

Merci pour votre message.

Suite à votre retour, nous venons d'appliquer un correctif ainsi que d'ajouter le query param 'src_url'.
La mise à jour sera déployée Lundi matin.

En vous souhaitant un excellent weekend,
L'équipe de l'Annuaire des Entreprises
