### ISSUE TITLE
App Crash on chunk load error

### ISSUE THREAD

**Issue by rmonnier9** [annuaire-entreprises-data-gouv-fr/site#1258]
Avec une mauvaise connexion on se prend des chunk load error, qui font crasher l'app. Ecran blanc avec 500.
Même comportement en cas de déploiement, ou les chunks peuvent disparaitre pendant le chargement d'une page.
Le comportement idéal serait d'avoir un bandeau ou un warning qui dit rechargez la page, mais pas un crash complet de l'App (le HTML est valide)

![Image](https://github.com/user-attachments/assets/36a31cc3-4005-40ee-85d1-ba6514e0c482)

Autre cas d’erreur :
Page rechercher -> clic sur une page -> probablement un chunk load et la page recherche erreur s'affiche brièvement
https://errors.data.gouv.fr/organizations/sentry/issues/140538/?query=is%3Aunresolved&referrer=issue-stream

**Comment by XavierJp** [comment]
closing as duplicate with
