### ISSUE TITLE
CIBTP

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1272]
## Nouvelle donnée dans l'espace agent
- https://entreprise.api.gouv.fr/catalogue/cibtp/attestations_cotisations_conges_payes_chomage_intemperies
- scope dédié cibtp

## Questions 
- [ ] interrogation par siret ? Une réponse par entreprise ?

**Comment by rmonnier9** [comment]
En profiter pour revoir les scopes / droits : 
- lors de Data.sub, pas évident de trouver où ajouter les scopes
- trop de copier/coller
