### ISSUE TITLE
UseRouter in <FilterMenu />

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#317]
Use `Next/Router` in form submit in `<FilterMenu />` : 
- on "Appliquer"
- on "Effacer"

## Mount Filters on click
Once we moved to `Next/Router`, we change the way the `<Filter />`are mounted. Currently they are always in DOM, but hidden. With the router, we can change that and only mount them on click.

**Comment by yoanficadiere** [comment]
This should be implement after the migration to server component
