### ISSUE TITLE
[info] Difficulté à déployer l'API et la db annuaire-entreprise

### ISSUE THREAD

**Issue by stouch** [annuaire-entreprises-data-gouv-fr/site#377]
## Votre demande de feature est-elle liée à un problème ?

Non

## L’amélioration que vous avez en tête

Simplification.

## Les alternatives possibles

Pour information, j'ai pu déployer en local une version simplifiée de vos repo (mes tests via Airflow n'étaient pas concluants et je ne voulais pas être dépendants de vos outils de monitoring etc). J'avais seulement besoin de la db et du moteur de recherche, et je me permets donc de vous en partager le code ici : https://github.com/stouch/annuaire-entreprises-fr-docker

Merci pour votre travail sur ces repo, le code a été facile à adapter.

**Comment by XavierJp** [comment]
Merci beaucoup !
