### ISSUE TITLE
[Data] cohérence des pages

### ISSUE THREAD

**Issue by acceleratorlastorder** [annuaire-entreprises-data-gouv-fr/site#467]
Bonjour,

Il semble que lorsqu'on accède à l'onglet "Dirigeants", si une personne choisit de ne pas transmettre ses données, elles ne sont effectivement pas affichées. Ceci est une bonne chose, car cela fonctionne comme prévu.

![image](https://user-images.githubusercontent.com/22743445/233818596-04f94dc6-fbd9-434a-937a-97fc9fdcc41f.png)

Cependant, je me demande quelle est l'utilité de cette fonctionnalité, étant donné qu'il suffit d'aller sur "Justificatif d'immatriculation" ou "Annonces", puis de cliquer sur le bouton de téléchargement pour accéder aux informations des dirigeants concernés.

Cordialement,

**Comment by XavierJp** [comment]
Bonjour, 
Depuis la création de cette issue, le bouton justificatif a également été caché.
