### ISSUE TITLE
Recherche par établissement impossible

### ISSUE THREAD

**Issue by pyrog** [annuaire-entreprises-data-gouv-fr/site#5]
Par exemple la recherche "[Kitchen academy Annecy](https://annuaire-entreprises.data.gouv.fr/rechercher?terme=Kitchen+academy+Annecy)" ne trouve pas l'établissement [44213327800360](https://annuaire-entreprises.data.gouv.fr/etablissement/44213327800360) :

_Aucune entité n’a été trouvée pour “Kitchen academy Annecy”
Nous vous suggérons de vérifier l’orthographe du nom, du SIRET, ou de l'adresse que vous avez utilisé._

**Comment by lmagreault** [comment]
Idem "Chez Georges" à Lons-le-Saunier ne ressort pas l'établissement [88977756100016](https://annuaire-entreprises.data.gouv.fr/etablissement/88977756100016)

**Comment by rmonnier9** [comment]
Nous fermons ce fil car le problème semble résolu par des correctifs passés :

https://annuaire-entreprises.data.gouv.fr/rechercher?terme=Kitchen+academy+Annecy
-> Le résultat est désormais correct

https://annuaire-entreprises.data.gouv.fr/rechercher?terme=Chez+Georges+Lons-le-Saunier
-> Il n'y a pas le résultat attendu car l'établissement est fermé : https://annuaire-entreprises.data.gouv.fr/etablissement/88977756100016?redirected=1
