### ISSUE TITLE
Dirigeant qui apparaît dans les résultats mais pas sur la page entreprise

### ISSUE THREAD

**Issue by mquandalle** [annuaire-entreprises-data-gouv-fr/site#615]
Certains dirigeants affichés sur la page de résultat de la recherche sont introuvables si on cherche dans les dirigeants / bénéficiaires effectifs.

Par exemple Margaux B. : https://annuaire-entreprises.data.gouv.fr/rechercher?terme=la+marmotte&fn=margaux&n=bailly, introuvable sur la société "La Marmotte", ni aucun de ses établissements.

![image](https://github.com/etalab/annuaire-entreprises-site/assets/1730702/7ce5cbe4-9d1c-421c-a472-f30c46a9043a)

**Comment by XavierJp** [comment]
Merci @mquandalle on va regarder ça

**Comment by XavierJp** [comment]
@mquandalle malheurreusement je reviens sur ce ticket un peu tard et je ne parviens pas vraiment a reproduire le problème. 

Mais je vois une différence entre les dirigeants dans la recherche et ceux affichés sur la page dirigeants : 
https://annuaire-entreprises.data.gouv.fr/dirigeants/834267809

@HAEKADI qu'en penses tu ? 

Je mets ca au prochain sprint

**Comment by HAEKADI** [comment]
@mquandalle Merci pour le signalement. Il s'agit bien d'un incohérence du côté du RNE. 
J'ai ouvert une issue sur l'infrastructure pour corriger ce problème. Tu peux la suivre ici https://github.com/annuaire-entreprises-data-gouv-fr/search-infra/issues/321.
