### ISSUE TITLE
[Sentry] ChunkLoadErrors causé par une navigation trop rapide et une connectivité lente

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#969]
https://sentry.io/answers/chunk-load-errors-javascript/

**Comment by johangirod** [comment]
Une piste intéressante soulevée par un [thread StackOverflow](https://stackoverflow.com/questions/69047420/webpack-code-splitting-chunkloaderror-loading-chunk-x-failed-but-the-chunk-e#comment128902997_69047420)

J'ai réussi à reproduire l'erreur en naviguant rapidement entre les pages. La requête du chunk est donc annulée avant le changement de page, ce qui causerait le `ChunkLoadError`.

![Image](https://github.com/annuaire-entreprises-data-gouv-fr/site/assets/1775934/e140e2eb-9972-47c4-98c7-551d24ae7654)

La bonne nouvelle, c'est que la page d'erreur ne s'affiche «que» pendant le chargement de la prochaine page. Dès que celle-ci a fini, elle s'affiche bien.

Si c'en est bien la cause principale, cette erreur n'aurait pas lieu si on utilisait le composant `Link` de Next, puisque le chargement du chunk précédent ne serait pas arrêté. Je pense qu'il faut qu'on se repose la question de ce qu'on gagne à ne pas faire le switch vs ce qu'on y perd.

Je réfléchis à une solution de contournement en attendant.

**Comment by johangirod** [comment]
J'ai trouvé une idée pour améliorer l'experience usager dans ce cas.

1. Créer un nouveau dossier parent avec un `layout.js` pour factoriser toute la partie au-dessus des onglets pour les routes entreprises, dirigeants, etc...
2. Ajouter un `error.js` au même niveau qui affiche « Chargement en cours » lorsque l'erreur est une instance de `ChunkLoadError`  et qu'un évènement de changement de page a été détecté (à peu près la même logique utilisé [pour requalifier les TypeError dans le client http frontend](https://github.com/annuaire-entreprises-data-gouv-fr/site/blob/344ee05fc947ceeef044bc19eaa07227759808b5/utils/network/frontend/index.ts#L78-L94)

Cela permettra d'afficher un état intermédiaire de chargement :

![Image](https://github.com/annuaire-entreprises-data-gouv-fr/site/assets/1775934/9c559de2-5b7e-41ab-977e-20aa1b924c9b)
