### ISSUE TITLE
Monitoring : Remontée des KPI espace agent

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#977]
Remontée des KPIs suivants :  
- [x] nb de visites d'agents connectés (déjà sur stats)
- [x] nb d'orgas distinctes #976
- [x] nb de siren différents consultés #976
- [ ] répartition des cas d'usage

Mode de consultation
- Soit un rapport kibana
- Soit exposés sur /stats
- Soit un hybride des deux

**Comment by johangirod** [comment]
C'est fait avec le dashboard Kibana
